"""BANE

Revision ID: caacb0a1408e
Revises: 
Create Date: 2026-05-24 12:20:05.627976

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'caacb0a1408e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'REVIEWER', 'READONLY', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('ai_systems',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('version', sa.String(length=100), nullable=True),
    sa.Column('owner_team', sa.String(length=255), nullable=True),
    sa.Column('tech_stack', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('deployment_env', sa.String(length=100), nullable=True),
    sa.Column('use_case', sa.Text(), nullable=True),
    sa.Column('data_types', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_autonomous', sa.Boolean(), nullable=False),
    sa.Column('affects_persons', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'UNDER_REVIEW', 'COMPLIANT', 'NON_COMPLIANT', 'EXEMPTED', name='systemstatus'), nullable=False),
    sa.Column('current_risk_category', sa.Enum('PROHIBITED', 'HIGH_RISK', 'LIMITED_RISK', 'MINIMAL_RISK', name='riskcategory'), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('actor_email', sa.String(length=255), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=100), nullable=True),
    sa.Column('resource_id', sa.UUID(), nullable=True),
    sa.Column('input_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('output_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('payload_hash', sa.String(length=64), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('request_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource_id'), 'audit_logs', ['resource_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource_type'), 'audit_logs', ['resource_type'], unique=False)
    op.create_table('model_cards',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ai_system_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('model_name', sa.String(length=255), nullable=False),
    sa.Column('model_type', sa.String(length=100), nullable=True),
    sa.Column('architecture', sa.String(length=255), nullable=True),
    sa.Column('framework', sa.String(length=100), nullable=True),
    sa.Column('license', sa.String(length=100), nullable=True),
    sa.Column('training_datasets', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('preprocessing_steps', sa.Text(), nullable=True),
    sa.Column('known_biases', sa.Text(), nullable=True),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('evaluation_procedure', sa.Text(), nullable=True),
    sa.Column('limitations', sa.Text(), nullable=True),
    sa.Column('out_of_scope_uses', sa.Text(), nullable=True),
    sa.Column('ethical_considerations', sa.Text(), nullable=True),
    sa.Column('risk_level', sa.String(length=50), nullable=True),
    sa.Column('conformity_measures', sa.Text(), nullable=True),
    sa.Column('human_oversight', sa.Text(), nullable=True),
    sa.Column('developer_contact', sa.String(length=255), nullable=True),
    sa.Column('dpo_contact', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', 'ARCHIVED', name='modelcardstatus'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ai_system_id'], ['ai_systems.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pii_scans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ai_system_id', sa.UUID(), nullable=True),
    sa.Column('scanned_by', sa.UUID(), nullable=True),
    sa.Column('source_type', sa.Enum('FILE', 'TEXT', 'DATABASE_SAMPLE', name='scansourcetype'), nullable=False),
    sa.Column('source_name', sa.String(length=255), nullable=True),
    sa.Column('source_hash', sa.String(length=64), nullable=True),
    sa.Column('total_items', sa.Integer(), nullable=False),
    sa.Column('pii_found', sa.Boolean(), nullable=False),
    sa.Column('findings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('entity_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('confidence_threshold', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', name='scanstatus'), nullable=False),
    sa.Column('risk_level', sa.Enum('CRITICAL', 'HIGH', 'MEDIUM', 'LOW', 'NONE', name='piiscanrisklevel'), nullable=True),
    sa.Column('recommendations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ai_system_id'], ['ai_systems.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['scanned_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pii_scans_created_at'), 'pii_scans', ['created_at'], unique=False)
    op.create_table('risk_assessments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ai_system_id', sa.UUID(), nullable=False),
    sa.Column('assessed_by', sa.UUID(), nullable=True),
    sa.Column('questionnaire', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('score_details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('total_score', sa.Integer(), nullable=False),
    sa.Column('risk_category', sa.String(length=50), nullable=False),
    sa.Column('justification', sa.Text(), nullable=True),
    sa.Column('ai_act_articles', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('required_actions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('valid_until', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ai_system_id'], ['ai_systems.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['assessed_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('risk_assessments')
    op.drop_index(op.f('ix_pii_scans_created_at'), table_name='pii_scans')
    op.drop_table('pii_scans')
    op.drop_table('model_cards')
    op.drop_index(op.f('ix_audit_logs_resource_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_resource_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_table('ai_systems')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
